services:
  db:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: sherlotracks
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 4G

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8800:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./public:/public

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3300:3300"
    environment:
      - VITE_API_URL=http://192.168.10.211:8800
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
